all: slides.html

slides.html: preamble.html main.html intro-and-isa-semantics.html scenarios.html synthesis.html epilogue.html
	cat preamble.html main.html intro-and-isa-semantics.html scenarios.html synthesis.html epilogue.html > slides.html

clean:
	rm slides.html